version: "2.3"
services:
  dev:
    runtime: nvidia
    build:
      context: .
    volumes:
      - ${HOME}/data:/data
      - ${PWD}:/work
    tty: true
    ipc: host  # necessary to avoid torch dataloader error
